### ISSUE TITLE
Error package Discord.Addons.PassiveInteractive not found

### ISSUE THREAD

**Issue by HarmoGlace** [PassiveModding/ServerSaverSelf#1]
Hi,

With the latest version, when I try to launch the .exe (I'm on windows), I have this error : 

"Error:
  An assembly specified in the application dependencies manifest (ServerCopierSelf.deps.json) was not found:
    package: 'Discord.Addons.PassiveInteractive', version: '2.0.2-Beta'
    path: 'lib/netstandard2.0/Discord.Addons.Interactive.dll'"

Can you help me please ?

**Comment by PassiveModding** [comment]
run the exe that is found in the publish folder, not the one in the main folder
